[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  ASTRO_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22"
  NPM_VERSION = "10.9.2"
